version: '3.1'

services:
  pg_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /docker_volume/v2_6_3/:/var/lib/mysql
      - /docker_volume/v1_6_2/:/var/backup
    ports:
      - 3306



    
      CREATE USER test@localhost WITH
      MAX_QUERIES_PER_HOUR 100
      PASSWORD EXPIRE INTERVAL 120 DAY 
      IDENTIFIED BY 'password';