version: '3.1'

services:
  pg_db: postgres:12
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=test-admin-user
      - POSTGRES_DB=test_db
    volumes:
      - /root/base:/var/lib/postgresql/data
      - /root/backup_sql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432