---
all:
  hosts:
    server-01:
      ansible_host: 51.250.20.122
    #server-02:
    #  ansible_host: 178.154.255.6
prod:
  hosts:
    server-01:
      ansible_host: 51.250.20.122
    #server-02:
    #  ansible_host: 178.154.255.6
test:
  hosts:
    server-01:
      ansible_host: 51.250.20.122
    #server-02:
    #  ansible_host: 178.154.255.6