{
 "title": "Netology Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IDLE 100%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\n100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"UNIX\",mode=\"idle\"}[1m])) * 100)\r"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_http_requests_total{job=\"prometheus\", code=\"200\"}"
    },
    {
     "expr": "prometheus_http_requests_total{job=\"prometheus\", code=\"400\"}"
    }
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"172.22.12.141:9182\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "FREE_MEM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free memory WIN" }
   ]
  },
  {
   "title": "HDD",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)"
    }
   ]
  },
  {
   "title": "CPU 15M",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"SERVER\"}[15m])\r",
     "legendFormat": "CPU 15M"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\r\nnode_network_receive_bytes_total{device=\"eth0\", instance=\"172.29.252.197:9100\", job=\"UNIX\"}",
     "legendFormat": "network"
    }
   ]
  },
  {
   "title": "CPU 5M",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"SERVER\"}[5m])\r",
     "legendFormat": "CPU 5M"
    }
   ]
  },
  {
   "title": "CPU 1M",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode, instance) (rate(process_cpu_seconds_total{job=\"SERVER\"}[1m]))\r",
     "legendFormat": "CPU 1M"
    }
   ]
  }
 ]
}