---
- name: Playbook  
  hosts: prod
  tasks:
  - name: Update apt-get repo and cache
    become: yes
    apt: 
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600 
  - name: Download kubectl
    become: yes
    ansible.builtin.shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - name: Copy file with owner and permissions
    become: yes
    ansible.builtin.copy:
      src: ./kubectl
      dest: /usr/local/bin/kubectl
      remote_src: yes
  - name: Changing perm of "kubectl", adding "+x"
    become: yes
    ansible.builtin.file:
      path: /usr/local/bin/kubectl
      owner: root
      group: root
      mode: '777'
      remote_src: yes
  - name: Install
    become: yes
    apt:
      name: docker.io
      state: present
  - name: Download minikube
    become: yes
    ansible.builtin.shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: Copy file with owner and permissions
    become: yes
    ansible.builtin.copy:
      src: ./minikube
      dest: /usr/local/bin/
      remote_src: yes
    - name: Changing perm of "minikube", adding "+x"
    become: yes
    ansible.builtin.file:
      dest: /usr/local/bin/minikube
      owner: root
      group: root
      mode: '777'
      remote_src: yes

  

  